language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge
  allow_failures:
    - php: 7.1
    - php: hhvm

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - composer test

after_success:
  - php vendor/bin/coveralls -v
